### PR TITLE
Improvements and so on

### PR DESCRIPTION
**Pull request by IMAN4K**
Signed-off-by: Iman Ahmadvand iman72411@gmail.com (github: @IMAN4K)

I just didn't touch `Dial` section of code base, but will do it in coming days.
And `GPRS` & `IP` `APIs` should be added

### CODE REVIEW

**Comment by skorokithakis** [comment]
Oh man, this is huge. Can you split it into multiple smaller PRs? It will take me ages to review like this, and I can't really test it :/

**Comment by IMAN4K** [comment]
The PRs are already split :)
I suggest creating new `dev` branch to adding changes step by step then merge to master as new release.
BTW i have tested with ESP8266 in last 25 days!

Regards.
IMAN.

**Comment by skorokithakis** [comment]
What do you mean "already split"? It's one large PR, isn't it? I'm also not sure what you mean by creating a dev branch...

**Comment by IMAN4K** [comment]
I mean there are 8 commit in this PR so you can easily review changes in each commit right?
I prefer not to put all changes directly to master, for that you must create new branch named `dev` in addition to `master`

That's all.

**Pull request closed without merging**
