### PR TITLE
Enable to compile for arduino boards

### PR DESCRIPTION
**Pull request by 1technophile**
Currently build is working with esp8266 but not with arduino. By adding macro depending on the board we can build now the library on Arduino or ESP8266.

### CODE REVIEW

**Comment by skorokithakis** [comment]
Would it not be easier to just `#define _min min`?

**Comment by 1technophile** [comment]
with a condition about which board is compiled I suppose?

**Comment by skorokithakis** [comment]
Yep, exactly.

**Comment by 1technophile** [comment]
yes we can do it like that, it will factorize the modification

**Comment by skorokithakis** [comment]
Looks great now, thanks! There are some whitespace changes that need to be fixed, could you fix those so I can merge?

Also, I don't know why the functions are `_min` instead of `min`, another person made that change and I don't know the rationale. The ESP8266 does support `min` as well, though...

**Comment by 1technophile** [comment]
With previous version of ESP8266 arduino board not, but it is now maybe the case, did you try to build with min?

**Comment by skorokithakis** [comment]
Not recently, but I can. It used to be with min originally, and it worked fine, but someone changed it and I don't know why. I thought it was an improvement, but apparently not.

**Comment by 1technophile** [comment]
I changed it due to build error with ESP8266

**Comment by skorokithakis** [comment]
Oh hmm, well we can merge yours and I'll try mine when I get home and see.

**Pull request merged**
